export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const FIND_RESPONSE_REQUEST = "FIND_RESPONSE_REQUEST";
export const FIND_RESPONSE_SUCCESS = "FIND_RESPONSE_SUCCESS";
export const FIND_RESPONSE_FAILURE = "FIND_RESPONSE_FAILURE";